version: '3'
services:
  dev:
    image: docker-node-template:dev
    container_name: docker-node-template-dev
    volumes:
      - ../node_modules:/app/node_modules
      - ../:/app

    stop_signal: SIGKILL
    working_dir: /app
    command: sh -c "pnpm i && pnpm run dev"
    init: true
    tty: true
    stdin_open: true